default:
  tags:
    - agargiulo-ci-cd

stages:
  - test

terraform_12_fmt_check:
  stage: test
  image:
    name: hashicorp/terraform:0.12.29
    entrypoint: [ "" ]
  script:
    - terraform --version
    - terraform fmt -diff -check

terraform_13_fmt_check:
  stage: test
  image:
    name: hashicorp/terraform:0.13.5
    entrypoint: [ "" ]
  script:
    - terraform --version
    - terraform fmt -diff -check

terraform_latest_fmt_check:
  stage: test
  image:
    name: hashicorp/terraform:light
    entrypoint: [ "" ]
  script:
    - terraform --version
    - terraform fmt -diff -check
  allow_failure: true
